# Generated by Django 3.1.6 on 2021-02-15 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_auto_20210215_1322'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='thumbnail',
            field=models.ImageField(upload_to='uploads/'),
        ),
    ]
