# Generated by Django 3.1.6 on 2021-02-15 14:45

from django.db import migrations, models
import django.db.models.deletion
import events.models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_auto_20210215_1336'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReservationCode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.IntegerField(default=events.models.random_string)),
                ('reserved', models.BooleanField(default=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.event')),
            ],
        ),
    ]
