# Generated by Django 3.1.6 on 2021-02-15 15:09

from django.db import migrations, models
import events.models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_reservationcode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservationcode',
            name='code',
            field=models.CharField(default=events.models.random_string, max_length=10),
        ),
    ]
